// file for languages that can be selected by user
/* export const languageDictionary = {
    'ar': 'Arabic',
    'bg': 'Bulgarian',
    'ca': 'Catalan, Valencian',
    'zh': 'Chinese',
    'cn': 'Chinese', 
    'cs': 'Czech',
    'da': 'Danish',
    'nl': 'Dutch, Flemish',
    'en': 'English',
    'fi': 'Finnish',
    'fr': 'French',
    'de': 'German',
    'el': 'Greek',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hu': 'Hungarian',
    'id': 'Indonesian',
    'it': 'Italian',
    'ja': 'Japanese',
    'kn': 'Kannada',
    'ko': 'Korean',
    'ms': 'Malay',
    'no': 'Norwegian',
    'fa': 'Persian',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ro': 'Romanian, Moldavian, Moldovan',
    'ru': 'Russian',
    'sr': 'Serbian',
    'sk': 'Slovakian',
    'es': 'Spanish, Castilian',
    'sv': 'Swedish',
    'tl': 'Tagalog',
    'ta': 'Tamil',
    'te': 'Telugu',
    'th': 'Thai',
    'tr': 'Turkish',
    'uk': 'Ukrainian',
  };
  */